#Private DockerHub Web App Image

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicdpipeline-server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cicdpipeline-server
  template:
    metadata:
      labels:
        app: cicdpipeline-server
    spec:
      containers:
      - image: ericincloud/cicdpipeline-server:latest
        name: cicdpipeline-server
        ports:
        - containerPort: 8080
        command: ["gunicorn"]
        args: ["-w", "4", "-b", ":8080", "app:app"]
      imagePullSecrets:
      - name: regcred
