#For Web App not NGINX web server

apiVersion: v1
kind: Service
metadata:
  name: cal-web-app
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: cicdpipeline-server
  type: LoadBalancer
